---
title: "Table 1. Sociodemographic and health history characteristics of women participating in the WHI by abuse experience at baseline (N = 83,145)"
output:
  word_document:
    reference_docx: word_style_template_01.docx
---

```{r setup, include=FALSE}
# Load packages
library(tidyverse)

# Load functions
source("../R scripts/table_1_functions.R")
```

```{r load_data, include=FALSE}
baseline_only <- read_rds(path = "../data/baseline_only.rds")
no_abuse <- read_rds(path = "../data/no_abuse.rds")
any_abuse <- read_rds(path = "../data/any_abuse.rds")
verbal_only <- read_rds(path = "../data/verbal_only.rds")
physical_only <- read_rds(path = "../data/physical_only.rds")
verbal_and_physical <- read_rds(path = "../data/verbal_and_physical.rds")
```

<!-- Group N's -->

```{r Ns, include=FALSE}
# Add n's to table
table_01 <- tibble(
  variable = "",
  class = "",
  no_abuse = get_n(no_abuse) %>% as.character(),
  any_abuse = get_n(any_abuse) %>% as.character(),
  verbal_only = get_n(verbal_only) %>% as.character(),
  physical_only = get_n(physical_only) %>% as.character(),
  verbal_and_physical = get_n(verbal_and_physical) %>% as.character()
)
```

<!-- Fill in values -->

```{r create_table_01, include=FALSE}
compare_groups <- c("no_abuse", "any_abuse", "verbal_only", "physical_only",
  "verbal_and_physical")

demo1 <- continuous_rows(variables = "age", groups = compare_groups)

demo2 <- categorical_rows(variables = c("age_group_f", "race_eth_f", "edu4cat_f",
  "inc5cat_f", "married_f", "sex_f", "ctos_f", "parity_f"),
  groups = compare_groups)

behavior1 <- continuous_rows(variables = c("texpwk", "alcswk", "f60caff"),
  groups = compare_groups)

behavior2 <- categorical_rows(variables = c("smoking_f", "horm_f", "hormnw_f",
  "ssri_f"), groups = compare_groups)

ment_hlth1 <- continuous_rows(variables = c("lifequal", "pshtdep", "bmi"),
  groups = compare_groups)

phys_hlth1 <- categorical_rows(variables = c("good_health_f", "hyst_f",
  "night_sweats_f", "hot_flashes_f", "vag_dry_f", "incont_f",
  "chronic_disease_f"), groups = compare_groups)

table_01 <- rbind(table_01, demo1, demo2, behavior1, behavior2, ment_hlth1, phys_hlth1)

# Improve readability
table_01 <- table_01 %>%
  mutate(
    # Sociodemographics
    variable = if_else(variable == "age", "Age, mean (sd)", variable),
    variable = if_else(variable == "age_group_f", "Age group, n (%)", variable),
    variable = if_else(variable == "race_eth_f", "Race and Ethnicity, n (%)", variable),
    variable = if_else(variable == "edu4cat_f", "Education, n (%)", variable),
    variable = if_else(variable == "inc5cat_f", "Income, n (%)", variable),
    variable = if_else(variable == "married_f", "Married, n (%)", variable),
    variable = if_else(variable == "sex_f", "Who you have had sex with, n (%)", variable),
    variable = if_else(variable == "ctos_f", "Clinical trial or observational study, n (%)", variable),
    variable = if_else(variable == "parity_f", "Parity, n (%)", variable),

    # Health Behavior
    variable = if_else(variable == "texpwk", "Physical activity (MET-hours/week), mean (sd)", variable),
    variable = if_else(variable == "alcswk", "Alcohol servings per week, mean (sd)", variable),
    variable = if_else(variable == "f60caff", "Dietary caffeine (mg), mean (sd)", variable),
    variable = if_else(variable == "smoking_f", "Smoking status, n (%)", variable),
    variable = if_else(variable == "horm_f", "Female hormones ever, n (%)", variable),
    variable = if_else(variable == "hormnw_f", "Female hormones now, n (%)", variable),
    variable = if_else(variable == "ssri_f", "Taking SSRI, n (%)", variable),

    # Health and Wellness
    variable = if_else(variable == "lifequal", "Quality of life, mean (sd)", variable),
    variable = if_else(variable == "pshtdep", "Shortened CES-D/DIS, mean (sd)", variable),
    variable = if_else(variable == "bmi", "Body Mass Index, mean (sd)", variable),
    variable = if_else(variable == "good_health_f", "Good or better health, n (%)", variable),
    variable = if_else(variable == "hyst_f", "Hysterectomy ever, n (%)", variable),
    variable = if_else(variable == "night_sweats_f", "Night sweats, n (%)", variable),
    variable = if_else(variable == "hot_flashes_f", "Hot flashes, n (%)", variable),
    variable = if_else(variable == "vag_dry_f", "Vaginal or genital dryness, n (%)", variable),
    variable = if_else(variable == "incont_f", "Ever leaked urine, n (%)", variable),
    variable = if_else(variable == "chronic_disease_f", "Chronic Disease, n (%)", variable)
  )

# Remove duplicate variable names for categorical variables
table_01 <- table_01 %>%
  group_by(variable) %>%
  mutate(
    x = duplicated(variable),
    x = if_else(variable == "", NA, x)
  ) %>%
  ungroup() %>%
  mutate(
    variable = if_else(x == TRUE, "", variable),
    variable = if_else(is.na(variable), "", variable),
    x = NULL
  )

rm(behavior1, behavior2, demo1, demo2, demo3, ment_hlth1, ment_hlth2,
   phys_hlth1, phys_hlth2, phys_hlth3, compare_groups, categorical_rows,
   continuous_rows, n_mean, n_percent)
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
table_01_kable <- knitr::kable(table_01, col.names = c(
  "Characteristic", "Class", 
  "No Abuse", 
  "Any Abuse", 
  "Verbal Only",
  "Physical Only", 
  "Verbal and Physical")
)

write_rds(table_01_kable, path = "table_01_kable.rds") # Save for use in dashboard
table_01_kable
```

```{r notes, include=FALSE}
# After knitting word table:
# Reorient to landscape
# Change all font to TNR 11
# Left justify title
# Remove bold from title - except "Table 1"
# Center columns 3 and above from top to bottom
# Adjust column widths as needed
# Add line break between age groups
# Add bottom border to table
```
