---
title: "Table 1. Sociodemographic and health history characteristics of women participating in the WHI by abuse experience at baseline (N = 83,169)"
output:
  word_document:
    reference_docx: word_style_template_01.docx
---

```{r setup, include=FALSE}
Sys.setenv(TZ = "US/Central")
library(tidyverse)
library(feather)
library(bfuncs)
```

```{r echo=FALSE}
baseline_only <- read_feather("../data/baseline_only.feather")

# Recode abuse_d_f to missing
baseline_only <- baseline_only %>% 
  mutate(
    abuse_d_f = fct_recode(abuse_d_f, NULL = "Abuse not measured", 
                           NULL = "Answered phyab, but not verbab",
                           NULL = "Answered verbab, but not phyab")
  ) %>% 
  filter(!is.na(abuse_d_f)) #83,169
```

```{r echo=FALSE}
# Create the table shell
# ---------------------
table <- tibble(
  variable = "",
  class = "",
  no_abuse = baseline_only %>% get_group_n(abuse_d_f == "No"),
  any_abuse = baseline_only %>% get_group_n(abuse_d_f == "Yes")
)

# Select data frame
# -----------------
df <- baseline_only

# Select group variable (columns)
# -------------------------------
group <- quo(abuse_d_f)

# Select variables (in order of appearance)
# -----------------------------------------
vars <- quos(age_group_f, race_eth_f, edu2cat_f, inc2cat_f, married_f, packyrs, 
             bmi4cat_f, hyst_f, incont_f, hypt_f, cvd_f, arthrit_f, 
             diab_combined_f, canc_f, hip55_f, good_health_f, pshtdep, ssri_f, 
             night_sweats_f, hot_flashes_f, vag_dry_f, hormnw_f, ctos_f)


# Build table
# -----------
for (i in seq_along(vars)) {
  
  # Figure out what type of variable it is
  class_var_i <- df %>% 
    pull(!! vars[[i]]) %>% 
    class()
  
  # If it's a categorical (character/factor) variable:
  # Calculate percent and 95% CI
  # Then, add that row to the table
  if (class_var_i == "character" || class_var_i == "factor") {
    
    row <- df %>% 
      filter(!(is.na(!! vars[[i]]))) %>% # filter out missing
      group_by(!! group, !! vars[[i]]) %>% 
      freq_table() %>% 
      format_table(stats = "n and row percent") %>% 
      spread(key = row_cat, value = n_percent_row) %>% 
      select(-row_var) %>% 
      rename(variable = col_var, class = col_cat, no_abuse = No, any_abuse = Yes) %>% 
      mutate(class = as.character(class)) # Need for bind_rows below
    
    # Append a blank row before each categorical variable
    # later this will create space to slide class levels over
    blank_row <- tibble(
      variable   = !! quo_name(vars[[i]]),
      class      = "",
      no_abuse = "",
      any_abuse    = ""
    )

    # Append to bottom of table
    table <- bind_rows(table, blank_row, row)
    
  # If it's a continuous variable:
  # Calculate mean and 95% CI
  # Then, add that row to the table 
  } else {
    
    row <- df %>% 
      group_by(!!group) %>% 
      mean_table(!!vars[[i]]) %>% 
      format_table(stats = "n and mean") %>% 
      spread(key = group_cat, value = n_mean) %>% 
      select(-group_var) %>% 
      rename(variable = response_var, no_abuse = No, any_abuse = Yes) %>% 
      mutate(class = "")

    # Append to bottom of table
    table <- bind_rows(table, row)
  }
}

# Clean up
rm(blank_row, df, row, vars, class_var_i, group, i)
```

```{r echo=FALSE}
# Drop some rows to make the table more succinct
table <- table %>% 
  filter(
    class != "Not College Graduate",
    class != "Not married or intimate relationship",
    class != "No"
  )
```


```{r echo=FALSE}
# Improve table appearance - automate somehow
table <- table %>%
  mutate(
    # Sociodemographics
    variable = if_else(variable == "age_group_f", "Age group, n (%)", variable),
    variable = if_else(variable == "race_eth_f", "Race and Ethnicity, n (%)", variable),
    variable = if_else(variable == "edu2cat_f", "Education, n (%)", variable),
    variable = if_else(variable == "inc2cat_f", "Income, n (%)", variable),
    variable = if_else(variable == "married_f", 
                       "Married or in an intimate relationship, n (%)", variable),

    # Health/health risk factors
    variable = if_else(variable == "packyrs", "Pack-years of Smoking, n (mean)", variable),
    variable = if_else(variable == "bmi4cat_f", "Body Mass Index, n (%)", variable),
    variable = if_else(variable == "hyst_f", "Hysterectomy ever, n (% yes)", variable),
    variable = if_else(variable == "incont_f", "Urinary incontinence ever, n (% yes)", variable),
    variable = if_else(variable == "hypt_f", "Hypertension ever, n (% yes)", variable),
    variable = if_else(variable == "cvd_f", "Cardiovascular disease ever, n (% yes)", variable),
    variable = if_else(variable == "arthrit_f", "Arthritis ever, n (% yes)", variable),
    variable = if_else(variable == "diab_combined_f", "Diabetes ever, n (% yes)", variable),
    variable = if_else(variable == "canc_f", "Cancer ever, n (% yes)", variable),
    variable = if_else(variable == "hip55_f", "Hip Fracture at Age 55 or Older, n (% yes)", variable),
    variable = if_else(variable == "good_health_f", "Good or better health, n (%)", variable),
    variable = if_else(variable == "pshtdep", "Shortened CES-D/DIS, n (mean)", variable),
    variable = if_else(variable == "ssri_f", "Current use of SSRI, n (% yes)", variable),

    # Menopausal symptoms/treatment variables that affect menopausal symptoms
    variable = if_else(variable == "night_sweats_f", "Night sweats, n (% yes)", variable),
    variable = if_else(variable == "hot_flashes_f", "Hot flashes, n (% yes)", variable),
    variable = if_else(variable == "vag_dry_f", "Vaginal or genital dryness, n (% yes)", variable),
    variable = if_else(variable == "hormnw_f", "Female hormones now, n (% yes)", variable),
    variable = if_else(variable == "ctos_f", "WHI study component, n (%)", variable)
  )
```

```{r echo=FALSE}
# Add blank row after each categorical variable - for sliding class levels over later
# For some reason, R automatically strips the leading white space. 
# The best work around I can come up with is to add dashes, then find and replaces dashes with white space in Word.
# For the variables that just had Yes/No options, condense to one row. 
table <- table %>% 
  group_by(variable) %>% 
  mutate(
    row = row_number(),
    class = stringr::str_replace(class, "^", "---"),
    drop = if_else(max(row) == 2 & any(class == "---Yes") & row == 1, 1L, 0L)
  ) %>% 
  filter(drop == 0) %>% 
  group_by(variable) %>%
  mutate(row = row_number()) %>% 
  ungroup() %>% 
  mutate(variable = if_else(row > 1, class, variable)) %>% 
  select(-class, -row, -drop)
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
table_kable <- knitr::kable(table, col.names = c(
  "Characteristic", 
  "No Abuse", 
  "Any Abuse")
)
table_kable
```

```{r notes, include=FALSE}
# After knitting word table:
# Change all font to TNR 11
# Remove bold from title - except "Table 1"
# Search and replace "---" with " "
# Autofit to window
# Center columns 2 & 3
# Add border above "Characteristic" row
# Remove border below "Characteristic" row
# Add border below "N =" row
# Adjust column widths as needed
# Add line break between variables
# Add bottom border to table
```
